const fs = require('fs');
const path = require('path');
const { loadStories } = require('./lib/load-stories');

const root = path.resolve(__dirname, '..');
const siteUrl = 'https://kyunolab.com';
const generatedMarker = '<!-- Generated by scripts/generate-tags.js. Do not edit this file directly. -->';
const styleVersion = '20260811-article-map-rail-fix';

const stories = loadStories(root);
const guides = readOptionalJson(path.join(root, 'data', 'guides.json'));
const articles = [...stories, ...guides];
const tagGroups = collectTagGroups(articles);
const tagStats = buildTagStats(tagGroups);

prepareTagDirectory();
for (const tagGroup of tagGroups) {
  writeTagPage(tagGroup);
}
updateSitemap(tagGroups);

logUrlStats(tagStats);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function readOptionalJson(filePath) {
  if (!fs.existsSync(filePath)) return [];
  return readJson(filePath);
}

function collectTagGroups(items) {
  const groups = new Map();

  for (const item of items) {
    for (const label of getTags(item)) {
      const normalized = normalizeTagLabel(label);
      const slug = slugify(normalized);
      const publicLabel = publicTagLabel(normalized);
      if (!slug) continue;
      if (!groups.has(slug)) {
        groups.set(slug, { label: publicLabel, slug, articles: [] });
      }
      groups.get(slug).articles.push(toArchiveArticle(item));
    }
  }

  return Array.from(groups.values())
    .filter((group) => group.articles.length > 0)
    .map((group) => ({
      ...group,
      description: getTagDescription(group),
      indexable: isIndexableTagGroup(group),
      articles: sortArticles(group.articles),
      lastmod: newestDate(group.articles)
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
}

function getTags(item) {
  const values = Array.isArray(item.tags) && item.tags.length ? item.tags : [item.tag];
  return Array.from(new Set(values.map((tag) => String(tag).trim()).filter(Boolean)));
}

function normalizeTagLabel(label) {
  const value = String(label || '').trim();
  const key = value.toLowerCase();
  const aliasMap = new Map([
    ['도깨비 전설', '도깨비'],
    ['한국 도깨비', '도깨비'],
    ['도깨비 이야기', '도깨비'],
    ['구미호 전설', '구미호'],
    ['한국 구미호', '구미호'],
    ['아홉 꼬리 여우', '구미호'],
    ['인어 전설', '인어'],
    ['바다 인어', '인어'],
    ['인어 이야기', '인어'],
    ['일본 요괴', '요괴'],
    ['요괴 이야기', '요괴'],
    ['요괴 전설', '요괴']
  ]);

  return aliasMap.get(key) || value;
}

function publicTagLabel(label) {
  const value = String(label || '').trim();
  if (/^source status$/i.test(value)) return 'Source Basis';
  return value;
}

function getTagDescription(group) {
  const count = group.articles.length;
  const categorySet = new Set(group.articles.map((article) => article.category).filter(Boolean));
  if (count < 3) return '';
  if (categorySet.size < 1) return '';
  return `A focused archive path for ${group.label}, collecting ${count} related Kyunolab stories across ${categorySet.size} shelf${categorySet.size === 1 ? '' : 'ves'}.`;
}

function isIndexableTagGroup(group) {
  return group.articles.length >= 3 && Boolean(getTagDescription(group)) && group.articles.length > 0;
}

function toArchiveArticle(item) {
  return {
    title: item.title,
    excerpt: item.excerpt || item.metaDescription || '',
    category: item.category || 'Archive Record',
    categorySlug: item.categorySlug || '',
    readTime: item.readTime || '',
    url: item.url || `/stories/${item.slug}`,
    publishedAt: item.publishedAt || '',
    updatedAt: item.updatedAt || item.publishedAt || ''
  };
}

function sortArticles(items) {
  return [...items].sort((a, b) => {
    const bTime = Date.parse(b.updatedAt || b.publishedAt || '') || 0;
    const aTime = Date.parse(a.updatedAt || a.publishedAt || '') || 0;
    if (bTime !== aTime) return bTime - aTime;
    return a.title.localeCompare(b.title);
  });
}

function newestDate(items) {
  const dates = items
    .map((item) => item.updatedAt || item.publishedAt)
    .filter(Boolean)
    .sort()
    .reverse();
  return dates[0] || currentDate();
}

function currentDate() {
  return new Date().toISOString().slice(0, 10);
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .trim()
    .replace(/&/g, ' and ')
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function prepareTagDirectory() {
  const tagDir = path.join(root, 'tags');
  fs.mkdirSync(tagDir, { recursive: true });

  for (const entry of fs.readdirSync(tagDir, { withFileTypes: true })) {
    const entryPath = path.join(tagDir, entry.name);
    if (entry.isFile() && entry.name.endsWith('.html')) {
      fs.unlinkSync(entryPath);
      continue;
    }
    if (entry.isDirectory()) {
      const indexPath = path.join(entryPath, 'index.html');
      if (fs.existsSync(indexPath) && fs.readFileSync(indexPath, 'utf8').includes(generatedMarker)) {
        fs.rmSync(entryPath, { recursive: true, force: true });
      }
    }
  }
}

function writeTagPage(tagGroup) {
  const outDir = path.join(root, 'tags', tagGroup.slug);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'index.html'), renderTagPage(tagGroup), 'utf8');
}

function renderTagPage(tagGroup) {
  const canonicalPath = `/tags/${tagGroup.slug}/`;
  const title = `Stories Tagged "${tagGroup.label}"`;
  const description = tagGroup.description || `A small internal archive path for Kyunolab stories connected to ${tagGroup.label}.`;
  const firstArticle = tagGroup.articles[0];
  const storyRows = renderStoryRowsWithMidAd(tagGroup.articles, 'ad-tag-mid-list');
  const robots = tagGroup.indexable ? 'index, follow' : 'noindex, follow';

  return `<!doctype html>
${generatedMarker}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} | Kyunolab Mystery Archive</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta name="robots" content="${robots}">
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:site_name" content="Kyunolab Mystery Archive">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${siteUrl}${canonicalPath}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="${siteUrl}${canonicalPath}">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32">
  <link rel="icon" href="/favicon-48x48.png" type="image/png" sizes="48x48">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="stylesheet" href="/styles.css?v=${styleVersion}">
</head>
<body class="home-portal-page">
  ${renderHomePortalHeader(canonicalPath)}

  <main class="home-shell home-portal-shell tag-portal-page">
    <div class="home-portal-layout">
      <div class="home-main-column">
        <section class="home-portal-lead tag-portal-lead" aria-label="${escapeAttr(tagGroup.label)} tag entrance">
          <article class="home-lead-story">
            <p class="label">Tag Archive</p>
            <h1>${escapeHtml(title)}</h1>
            <p>${escapeHtml(description)}</p>
            <a class="button" href="/categories.html">Browse categories</a>
          </article>
          <div class="home-known-list">
            <h2>Start with this tag</h2>
            ${tagGroup.articles.slice(0, 5).map(renderTagStarterLink).join('')}
          </div>
        </section>
        ${renderAdSlot('ad-tag-after-intro')}
        <section class="home-headline-desk archive-story-index" aria-label="${escapeAttr(tagGroup.label)} tagged stories">
          <div class="section-head"><h2>${escapeHtml(tagGroup.label)} Records</h2><span>${escapeHtml(`${tagGroup.articles.length} linked page${tagGroup.articles.length === 1 ? '' : 's'}`)}</span></div>
          <div class="archive-story-index-grid">
            <div class="story-list">
${storyRows}
            </div>
            <aside class="home-context-card">
              <p class="label">Tag road</p>
              <h3>Use tags as side streets, not the whole destination.</h3>
              <p>This page gathers related archive records and guides, then points readers back into full stories, category shelves, and newer records.</p>
              <div class="category-links"><a href="/archive.html">All Stories</a><a href="/newest.html">Newest Records</a><a href="/popular.html">Known Records</a></div>
            </aside>
          </div>
          <nav class="pagination" aria-label="Tag pagination">
            <div class="pagination-status">Page 1 of 1</div>
            <div class="pagination-links">
              <span class="page-link page-step is-disabled" aria-disabled="true">Previous</span>
              <span class="page-link is-current" aria-current="page">1</span>
              <span class="page-link page-step is-disabled" aria-disabled="true">Next</span>
            </div>
          </nav>
        </section>
      </div>

      <aside class="home-portal-rail" aria-label="Recommended archive paths">
        ${renderKyunolabNetworkCard()}
        <section class="rail-card rail-feature">
          <p class="rail-label">Start here</p>
          <a href="${escapeAttr(firstArticle.url)}"><strong>${escapeHtml(firstArticle.title)}</strong><span>${escapeHtml(firstArticle.category)}</span></a>
        </section>
        <section class="rail-card">
          <p class="rail-label">Archive roads</p>
          <a href="/categories.html">Browse all categories</a>
          <a href="/newest.html">Latest articles</a>
          <a href="/popular.html">Popular articles</a>
          <a href="/archive.html">Archive Index</a>
        </section>
      </aside>
    </div>
  </main>

  ${renderFooter()}
  <script defer src="/assets/global-search.js?v=${styleVersion}"></script>
</body>
</html>
`;
}

function renderTagStarterLink(article, index) {
  return `<a href="${escapeAttr(article.url)}"><span>${String(index + 1).padStart(2, '0')}</span><strong>${escapeHtml(article.title)}</strong><em>${escapeHtml(article.category)}</em></a>`;
}

function renderStoryRow(article) {
  const meta = [article.category, article.readTime].filter(Boolean).join(' - ');
  return `        <article class="story-row">
          <span class="tag">${escapeHtml(article.category)}</span>
          <h3><a href="${escapeAttr(article.url)}">${escapeHtml(article.title)}</a></h3>
          <p>${escapeHtml(article.excerpt)}</p>
          ${meta ? `<small>${escapeHtml(meta)}</small>` : ''}
        </article>`;
}

function renderAdSlot(slotName, extraClass = '') {
  const className = ['ad-slot', extraClass].filter(Boolean).join(' ');
  return `<aside class="${escapeAttr(className)}" data-ad-slot="${escapeAttr(slotName)}" aria-label="Advertisement"><span>Advertisement</span></aside>`;
}

function renderStoryRowsWithMidAd(articles, slotName) {
  const rows = articles.map(renderStoryRow);
  if (rows.length >= 7) rows.splice(6, 0, renderAdSlot(slotName));
  return rows.join('\n');
}

function renderHeader() {
  return renderHomePortalHeader('/');
}

function renderHomePortalHeader(currentPath = '/') {
  const pathForNav = normalizeNavPath(currentPath);
  return `<header class="home-portal-header">
    <div class="home-portal-header-inner">
      <div class="home-portal-topbar">
        <a class="home-portal-brand" href="/"><span class="home-portal-brand-mark"><img src="/icon-192.png" alt="" aria-hidden="true"></span><span><strong>Kyunolab Mystery Archive</strong><em>Legends, folklore, mysteries, and strange tales.</em></span></a>
        ${renderHomePortalSearchForm()}
      </div>
      <nav class="home-portal-nav" aria-label="Primary homepage navigation">
        ${homePortalNavLink('/', 'Home', pathForNav === '/')}
        ${homePortalNavLink('/popular.html', 'Known Stories', pathForNav === '/popular')}
        ${homePortalNavLink('/newest.html', 'Newest Stories', pathForNav === '/newest')}
        ${homePortalNavLink('/categories.html', 'Categories', pathForNav === '/categories' || pathForNav.startsWith('/categories/'))}
        ${homePortalNavLink('/mystery-board.html', 'Mystery Board', pathForNav === '/mystery-board' || pathForNav.startsWith('/mystery-board/'))}
        ${homePortalNavLink('/scripts/', 'Creator Library', pathForNav.startsWith('/scripts'))}
        ${homePortalNavLink('/tools.html', 'Tools', pathForNav === '/tools')}
        ${homePortalNavLink('/about.html', 'About', pathForNav === '/about')}
        ${homePortalNavLink('/hub.html', 'Hub', pathForNav === '/hub', 'home-portal-hub-link')}
      </nav>
      ${renderHomeSignSystem()}
    </div>
  </header>`;
}

function homePortalNavLink(href, label, isActive, extraClass = '') {
  const classes = [extraClass, isActive ? 'active' : ''].filter(Boolean).join(' ');
  const classAttr = classes ? ` class="${escapeAttr(classes)}"` : '';
  return `<a href="${href}"${classAttr}${isActive ? ' aria-current="page"' : ''}>${escapeHtml(label)}</a>`;
}

function renderHomePortalSearchForm() {
  return `<form class="site-search home-portal-search" action="/search/" method="get" role="search" aria-label="Search Kyunolab">
          <input type="hidden" name="type" value="archive">
          <label class="sr-only" for="tag-portal-search-query">Search query</label>
          <input id="tag-portal-search-query" name="q" class="site-search-input" type="search" placeholder="Search Kyunolab..." autocomplete="off" data-search-input>
          <button class="site-search-button" type="submit">Search</button>
        </form>`;
}

function renderHomeSignSystem() {
  return `<section class="home-sign-system" aria-label="Kyunolab reading paths">
          <div class="home-sign-intro">
            <p class="label">Start Here</p>
            <h2>Choose a story shelf first, then use the map when you want the wider site.</h2>
            <p>Begin with archive stories, open the full index, or cross into reading guides, creator material, and future tools.</p>
          </div>
          <div class="home-sign-links">
            <div>
              <h3>Browse Stories</h3>
              <a href="/categories/urban-legends.html">Urban Legends</a>
              <a href="/categories/internet-folklore.html">Internet Folklore</a>
              <a href="/categories/myths.html">Myths</a>
              <a href="/categories/strange-places.html">Strange Places</a>
            </div>
            <div>
              <h3>Use The Map</h3>
              <a href="/archive.html">All Stories</a>
              <a href="/mystery-board.html">Reading Guides</a>
              <a href="/scripts/">Creator Library</a>
              <a href="/tools.html">Tools</a>
            </div>
          </div>
          <div class="home-small-buildings">
            <h3>Site Notes</h3>
            <a href="/hub.html">Hub</a>
            <a href="/about.html">About Kyunolab</a>
            <a href="/fiction-disclaimer.html">Story and source notice</a>
          </div>
        </section>`;
}

function normalizeNavPath(value) {
  const clean = String(value || '/').replace(/^https?:\/\/[^/]+/i, '').replace(/[?#].*$/, '');
  if (clean === '/' || clean === '') return '/';
  const withoutHtml = clean.replace(/\.html$/, '');
  return withoutHtml.endsWith('/') && withoutHtml !== '/' ? withoutHtml.slice(0, -1) : withoutHtml;
}

function renderKyunolabNetworkCard() {
  return `<div class="rail-card rail-card-network">
        <p class="rail-label">Kyunolab Network</p>
        <strong>Creator Library</strong>
        <p>Free mystery YouTube scripts, Shorts scripts, image prompts, and thumbnail ideas for video creators.</p>
        <a class="button" href="/scripts/">Open Creator Library</a>
      </div>`;
}

function renderFooter() {
  return `<footer class="site-footer">
    <p><strong>Kyunolab Mystery Archive</strong> is a quiet story publication by Kyuno Lab, dedicated to legends, folklore, mysteries, and strange tales from the edges of memory.</p>
    <p><a href="/archive">Archive Index</a> - <a href="/newest">Newest</a> - <a href="/popular">Popular</a> - <a href="/categories">Categories</a> - <a href="/tools">Tools</a> - <a href="/hub">Hub</a> - <a href="/about">About</a> - <a href="/fiction-disclaimer">Story &amp; Source Notice</a> - <a href="/privacy">Privacy</a> - <a href="/rss.xml">RSS</a></p>
  </footer>`;
}

function updateSitemap(groups) {
  const sitemapPath = path.join(root, 'sitemap.xml');
  if (!fs.existsSync(sitemapPath)) return;

  const sitemap = fs.readFileSync(sitemapPath, 'utf8');
  const withoutOldTags = sitemap.replace(/\s*<url><loc>https:\/\/kyunolab\.com\/tags\/[^<]+<\/loc><lastmod>[^<]+<\/lastmod><\/url>/g, '');
  const tagUrls = groups
    .filter((group) => group.indexable)
    .map((group) => `  <url><loc>${siteUrl}/tags/${group.slug}/</loc><lastmod>${group.lastmod}</lastmod></url>`)
    .join('\n');

  const nextSitemap = withoutOldTags.replace(/\s*<\/urlset>\s*$/, `\n${tagUrls}\n</urlset>\n`);
  fs.writeFileSync(sitemapPath, nextSitemap, 'utf8');
}

function buildTagStats(groups) {
  const indexableTags = groups.filter((group) => group.indexable);
  const oneArticleTags = groups.filter((group) => group.articles.length === 1);
  const noindexTags = groups.filter((group) => !group.indexable);
  return {
    totalGeneratedTagUrls: groups.length,
    sitemapTagUrls: indexableTags.length,
    indexableTagUrls: indexableTags.length,
    noindexTagUrls: noindexTags.length,
    oneArticleTagUrls: oneArticleTags.length,
    relatedKeywordsGeneratedUrls: 0
  };
}

function logUrlStats(stats) {
  const storyUrlCount = stories.length;
  const categoryUrlCount = new Set(stories.map((story) => story.categorySlug).filter(Boolean)).size;
  const guideUrlCount = guides.length;
  const staticIndexableUrlCount = 9;
  const sitemapUrlCount = staticIndexableUrlCount + storyUrlCount + categoryUrlCount + guideUrlCount + stats.sitemapTagUrls;
  const totalGeneratedUrlCount = staticIndexableUrlCount + storyUrlCount + categoryUrlCount + guideUrlCount + stats.totalGeneratedTagUrls;

  console.log(`Generated ${stats.totalGeneratedTagUrls} tag archive pages.`);
  console.log('URL generation report:');
  console.log(`- Total generated URL count: ${totalGeneratedUrlCount}`);
  console.log(`- Sitemap included URL count: ${sitemapUrlCount}`);
  console.log(`- Index-allowed URL count: ${sitemapUrlCount}`);
  console.log(`- Story detail URL count: ${storyUrlCount}`);
  console.log(`- Tag page count: ${stats.totalGeneratedTagUrls}`);
  console.log(`- Noindex tag page count: ${stats.noindexTagUrls}`);
  console.log(`- One-article tag count: ${stats.oneArticleTagUrls}`);
  console.log(`- relatedKeywords-generated URL count: ${stats.relatedKeywordsGeneratedUrls}`);
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(value) {
  return escapeHtml(value);
}
