const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const siteUrl = 'https://kyunolab.com';
const generatedMarker = '<!-- Generated by scripts/generate-tags.js. Do not edit this file directly. -->';
const styleVersion = '20260702-engagement-ui';

const stories = readJson(path.join(root, 'data', 'stories.json'));
const guides = readOptionalJson(path.join(root, 'data', 'guides.json'));
const articles = [...stories, ...guides];
const tagGroups = collectTagGroups(articles);

prepareTagDirectory();
for (const tagGroup of tagGroups) {
  writeTagPage(tagGroup);
}
updateSitemap(tagGroups);

console.log(`Generated ${tagGroups.length} tag archive pages.`);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function readOptionalJson(filePath) {
  if (!fs.existsSync(filePath)) return [];
  return readJson(filePath);
}

function collectTagGroups(items) {
  const groups = new Map();

  for (const item of items) {
    for (const label of getTags(item)) {
      const slug = slugify(label);
      if (!slug) continue;
      if (!groups.has(slug)) {
        groups.set(slug, { label, slug, articles: [] });
      }
      groups.get(slug).articles.push(toArchiveArticle(item));
    }
  }

  return Array.from(groups.values())
    .filter((group) => group.articles.length > 0)
    .map((group) => ({
      ...group,
      articles: sortArticles(group.articles),
      lastmod: newestDate(group.articles)
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
}

function getTags(item) {
  const values = Array.isArray(item.tags) && item.tags.length ? item.tags : [item.tag];
  return Array.from(new Set(values.map((tag) => String(tag).trim()).filter(Boolean)));
}

function toArchiveArticle(item) {
  return {
    title: item.title,
    excerpt: item.excerpt || item.metaDescription || '',
    category: item.category || 'Archive Record',
    categorySlug: item.categorySlug || '',
    readTime: item.readTime || '',
    url: item.url || `/stories/${item.slug}`,
    publishedAt: item.publishedAt || '',
    updatedAt: item.updatedAt || item.publishedAt || ''
  };
}

function sortArticles(items) {
  return [...items].sort((a, b) => {
    const bTime = Date.parse(b.updatedAt || b.publishedAt || '') || 0;
    const aTime = Date.parse(a.updatedAt || a.publishedAt || '') || 0;
    if (bTime !== aTime) return bTime - aTime;
    return a.title.localeCompare(b.title);
  });
}

function newestDate(items) {
  const dates = items
    .map((item) => item.updatedAt || item.publishedAt)
    .filter(Boolean)
    .sort()
    .reverse();
  return dates[0] || currentDate();
}

function currentDate() {
  return new Date().toISOString().slice(0, 10);
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .trim()
    .replace(/&/g, ' and ')
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function prepareTagDirectory() {
  const tagDir = path.join(root, 'tags');
  fs.mkdirSync(tagDir, { recursive: true });

  for (const entry of fs.readdirSync(tagDir, { withFileTypes: true })) {
    const entryPath = path.join(tagDir, entry.name);
    if (entry.isFile() && entry.name.endsWith('.html')) {
      fs.unlinkSync(entryPath);
      continue;
    }
    if (entry.isDirectory()) {
      const indexPath = path.join(entryPath, 'index.html');
      if (fs.existsSync(indexPath) && fs.readFileSync(indexPath, 'utf8').includes(generatedMarker)) {
        fs.rmSync(entryPath, { recursive: true, force: true });
      }
    }
  }
}

function writeTagPage(tagGroup) {
  const outDir = path.join(root, 'tags', tagGroup.slug);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'index.html'), renderTagPage(tagGroup), 'utf8');
}

function renderTagPage(tagGroup) {
  const canonicalPath = `/tags/${tagGroup.slug}/`;
  const title = `Stories Tagged "${tagGroup.label}"`;
  const description = 'A collection of archive entries connected by this recurring story pattern.';
  const firstArticle = tagGroup.articles[0];
  const storyRows = tagGroup.articles.map(renderStoryRow).join('\n');

  return `<!doctype html>
${generatedMarker}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} | The Strange Archive</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${siteUrl}${canonicalPath}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="${siteUrl}${canonicalPath}">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="stylesheet" href="/styles.css?v=${styleVersion}">
</head>
<body>
  ${renderHeader()}

  <main class="article-shell article-layout">
    <aside class="article-rail article-rail-left" aria-label="Tag archive paths">
      <div class="rail-card">
        <p class="rail-label">This tag</p>
        <a href="${canonicalPath}">${escapeHtml(tagGroup.label)}</a>
        <a href="/categories.html">Browse all categories</a>
        <a href="/newest.html">Latest articles</a>
        <a href="/popular.html">Popular articles</a>
        <a href="/archive.html">Archive Index</a>
      </div>
    </aside>

    <div class="archive-page-main">
      <p class="label">Tag Archive</p>
      <h1 class="article-title">${escapeHtml(title)}</h1>
      <p class="deck">${escapeHtml(description)}</p>
      <div class="story-list">
${storyRows}
      </div>
      <nav class="pagination" aria-label="Tag pagination">
        <div class="pagination-status">Page 1 of 1</div>
        <div class="pagination-links">
          <span class="page-link page-step is-disabled" aria-disabled="true">Previous</span>
          <span class="page-link is-current" aria-current="page">1</span>
          <span class="page-link page-step is-disabled" aria-disabled="true">Next</span>
        </div>
      </nav>
    </div>

    <aside class="article-rail article-rail-right" aria-label="Recommended archive paths">
      <div class="rail-card rail-feature">
        <p class="rail-label">Start here</p>
        <a href="${escapeAttr(firstArticle.url)}"><strong>${escapeHtml(firstArticle.title)}</strong><span>${escapeHtml(firstArticle.category)}</span></a>
      </div>
      <div class="rail-card rail-card-subtle">
        <p class="rail-label">Same archive shelf</p>
        <a href="/newest.html">Newest Records</a>
        <a href="/popular.html">Popular Records</a>
        <a href="/mystery-board.html">Mystery Board</a>
      </div>
    </aside>
  </main>

  ${renderFooter()}
</body>
</html>
`;
}

function renderStoryRow(article) {
  const meta = [article.category, article.readTime].filter(Boolean).join(' - ');
  return `        <article class="story-row">
          <span class="tag">${escapeHtml(article.category)}</span>
          <h3><a href="${escapeAttr(article.url)}">${escapeHtml(article.title)}</a></h3>
          <p>${escapeHtml(article.excerpt)}</p>
          ${meta ? `<small>${escapeHtml(meta)}</small>` : ''}
        </article>`;
}

function renderHeader() {
  return `<header class="site-header">
    <div class="topline">A Kyuno Lab publication</div>
    <div class="header-inner">
      <a class="brand" href="/"><span class="brand-mark"><img src="/favicon.svg" alt="" aria-hidden="true"></span><span><strong>The Strange Archive</strong><em>Legends, folklore, mysteries, and strange tales.</em></span></a>
      <nav class="nav"><a href="/newest.html">Newest</a><a href="/popular.html">Popular</a><a href="/categories.html">Categories</a><a href="/mystery-board.html">Mystery Board</a><a href="/about.html">About</a></nav>
    </div>
  </header>`;
}

function renderFooter() {
  return `<footer class="site-footer">
    <p><strong>The Strange Archive</strong> is a quiet story publication by Kyuno Lab, dedicated to legends, folklore, mysteries, and strange tales from the edges of memory.</p>
    <p><a href="/archive.html">Archive Index</a> - <a href="/newest.html">Newest</a> - <a href="/popular.html">Popular</a> - <a href="/categories.html">Categories</a> - <a href="/about.html">About</a> - <a href="/fiction-disclaimer.html">Story &amp; Source Notice</a> - <a href="/privacy.html">Privacy</a> - <a href="/rss.xml">RSS</a></p>
  </footer>`;
}

function updateSitemap(groups) {
  const sitemapPath = path.join(root, 'sitemap.xml');
  if (!fs.existsSync(sitemapPath)) return;

  const sitemap = fs.readFileSync(sitemapPath, 'utf8');
  const withoutOldTags = sitemap.replace(/\s*<url><loc>https:\/\/kyunolab\.com\/tags\/[^<]+<\/loc><lastmod>[^<]+<\/lastmod><\/url>/g, '');
  const tagUrls = groups
    .map((group) => `  <url><loc>${siteUrl}/tags/${group.slug}/</loc><lastmod>${group.lastmod}</lastmod></url>`)
    .join('\n');

  const nextSitemap = withoutOldTags.replace(/\s*<\/urlset>\s*$/, `\n${tagUrls}\n</urlset>\n`);
  fs.writeFileSync(sitemapPath, nextSitemap, 'utf8');
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(value) {
  return escapeHtml(value);
}
